### ISSUE TITLE
EPIC: Meals Endpoints

### ISSUE THREAD

**Issue by m-mrcr** [earl-stephens/om_nom#13]
The following represents the total components for completion of the Meals endpoints required within Week 1 Endpoints (_refer to individual issues for further explanation_):

- [x] GET /api/v1/meals
Returns all the meals in the database along with their associated foods

- [x] GET /api/v1/meals/:meal_id/foods
Returns all the foods associated with the meal with an id specified by :meal_id or a 404 if the meal is not found

- [x] POST /api/v1/meals/:meal_id/foods/:id
Adds the food with :id to the meal with :meal_id

- [ ] DELETE /api/v1/meals/:meal_id/foods/:id
Removes the food with :id from the meal with :meal_id
