### ISSUE TITLE
EPIC: Foods Endpoints

### ISSUE THREAD

**Issue by m-mrcr** [earl-stephens/om_nom#5]
The following represents the total components for completion of the Foods endpoints required within Week 1 Endpoints (_refer to individual issues for further explanation_):

- [x] **GET /api/v1/foods**
Returns all foods currently in the database

- [x] **GET api/v1/foods/:id**
Returns the food object with the specific :id you’ve passed in or 404 if the food is not found

- [x] **POST /api/v1/foods**
Allows creating a new food. If food is successfully created, the food item will be returned. If the food is not successfully created, a 400 status code will be returned. Both name and calories are required fields.

- [x] **PATCH /api/v1/foods/:id**
Allows one to update an existing food. If food is successfully updated (name and calories are required fields), the food item will be returned. If the food is not successfully updated, a 400 status code will be returned.

- [x] **DELETE /api/v1/foods/:id**
Will delete the food with the id passed in and return a 204 status code. If the food can’t be found, a 404 will be returned.
